Added alias tax meta field.
UCF/UCF-Colleges-Tax-Plugin pull request #1
Opened 2016-11-10 20:03 UTC by jmbarne3

Adds the 'alias' meta field to the Colleges taxonomy. We use this pretty often so the entire college name - i.e. College of Arts and Humanities - doesn't have to appear above a list of related objects. Instead the alias can be output - i.e. 'Arts and Humanities' or just 'Arts'. Also included in the diff is the removal of a specific directory name in the PLUGIN_URL constant. Instead using the `basename()` function to get the name of the current directory.

2016-11-10 20:23 UTC, cjg89 requested changes
Need to add a closing `</td>` on this line:
https://github.com/UCF/UCF-Colleges-Tax-Plugin/pull/1/commits/19ca8608f003bd5ca30c12d4c1dd4f844fec492d?w=1&ts=4#diff-3b4349e6cd7e54c49fcd799b0f4a3c3eR40

Otherwise this looks good to me!

2016-11-10 20:36 UTC, cjg89 commented
Comment test

2016-11-10 20:38 UTC, cjg89 approved these changes

2016-11-10 20:54 UTC, rjucf commented
Looks good to me

2016-11-14 15:09 UTC, keeeeeegan commented
Looks good

2016-11-14 15:10 UTC, merged